### ISSUE TITLE
Reporte de práctica

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-ybjs-jun#1]
[Reporte de práctica 1_S4.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-ybjs-jun/files/6780991/Reporte.de.practica.1_S4.pdf)

**Comment by Yabin-2021** [comment]
Anexo rúbrica para evaluar la práctica...
[Rúbrica de práctica de Base de Datos.docx](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-ybjs-jun/files/6781790/Rubrica.de.practica.de.Base.de.Datos.docx)
 
Utilizar el documento para evaluar y subirlo en PDF si es posible.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
